/**
 * Customer Email Builder template configuration.
 * Generated by template-editor.html.
 */
window.CUSTOMER_EMAIL_BUILDER_CONFIG = {
  "storageKey": "customerEmailBuilder.templateEdits",
  "templates": {
    "outOfStock": {
      "label": "Out of stock item",
      "subject": "Update on your CSU Bookstore order #{orderNumber}",
      "body": "Thank you for your order from the CSU Bookstore. Regrettably, we sold out of {item}, and it is currently unavailable.",
      "note": "Emailed customer regarding unavailable item{item}",
      "fields": {
        "item": true,
        "restockExpected": true,
        "stockOrderContents": true
      }
    },
    "substitutions": {
      "label": "Out of stock item with substitutions",
      "subject": "Substitution options for your CSU Bookstore order #{orderNumber}",
      "body": "Thank you for your order from the CSU Bookstore. Regrettably, one of the items in your order{item} is currently unavailable. We understand this is disappointing, but we have found the following possible substitutions that may fit your needs.",
      "note": "Emailed customer regarding unavailable item. Provided substitution options",
      "fields": {
        "item": true,
        "substitutions": true,
        "stockOrderContents": true
      }
    },
    "returnRequest": {
      "label": "Return request received",
      "subject": "We received your CSU Bookstore return request #{orderNumber}",
      "body": "We received your return request and are reviewing it. We will follow up with return instructions or any questions as soon as possible. Please keep the item and its packaging until you hear from us.",
      "note": "Confirmed receipt of customer's return request",
      "fields": {}
    },
    "orderCancellation": {
      "label": "Order cancellation",
      "subject": "Your CSU Bookstore order has been canceled #{orderNumber}",
      "body": "Your order has been canceled as requested. Any pending authorization should be released by your financial institution according to its normal processing time.",
      "note": "Canceled order and emailed customer confirmation",
      "fields": {}
    },
    "dayOneCancellation": {
      "label": "Day One Access/title cancellation",
      "subject": "Update for CSU Bookstore Order #{orderNumber}",
      "body": "Thank you for your course materials order from the CSU Bookstore. We are contacting to notify you that we are removing the Day One Access title “{dayOneTitle}” for {courseName} from #{orderNumber}.",
      "note": "Emailed customer regarding Day One Access title “{dayOneTitle}” for {courseName}",
      "fields": {
        "dayOne": true
      }
    },
    "shippingDelay": {
      "label": "Shipping delay",
      "subject": "Shipping update for your CSU Bookstore order #{orderNumber}",
      "body": "Your order is taking longer to ship than expected. We are working to send it as soon as possible and will email tracking information when it leaves the store. We apologize for the delay.",
      "note": "Emailed customer regarding shipping delay",
      "fields": {}
    },
    "pickupReminder": {
      "label": "Pickup reminder",
      "subject": "REMINDER: CSU Bookstore Order #{orderNumber} Is Awaiting Pick Up",
      "body": "Your CSU Bookstore order #{orderNumber} is ready for pickup.\n\nOrders may be picked up at the CSU Bookstore Pickup Counter on the lower level of the bookstore. Please have your order number available when you arrive.\n\nSummer pickup hours are Monday through Friday from 9:00 a.m. to 4:00 p.m. If you need assistance arranging pickup outside of these hours, please contact bookstoreorders@colostate.edu. \n\nIf you are unable to pick up the order yourself, another individual may do so on your behalf. Simply reply to this email with their name, and we will note on the order that they are authorized to pick it up.\n\nPlease pick up your order by {restockDate}. Orders not picked up by this date may be refunded and returned to inventory.\n\nIf you no longer need the items in your order, you may request cancellation at bookstore.colostate.edu/cancel.\n\nIf you have any questions, simply reply to this email, and we will be happy to assist you.\n",
      "note": "Sent customer pickup reminder for order packed on {packedDate}; advised restock/cancellation date of {restockDate}",
      "fields": {
        "pickup": true
      }
    },
    "finalPickupReminder": {
      "label": "Final Pickup Reminder",
      "subject": "Final pickup reminder for your CSU Bookstore order #{orderNumber}",
      "body": "This is a final reminder that your CSU Bookstore order #{orderNumber} is awaiting pickup.\n\nOur records indicate that your order has been ready for pickup since {packedDate}, and we previously contacted you on {firstReminderDate}.\n\nOrders may be picked up at the CSU Bookstore Pickup Counter on the lower level of the bookstore. Please bring your order number and a photo ID when picking up your order.\n\nIf you are unable to pick up the order yourself, another individual may do so on your behalf. Simply reply to this email with their name, and we will note on the order that they are authorized to pick it up.\n\nPlease pick up your order by {restockDate}. Orders not picked up by this date may be refunded and returned to inventory.\n\nIf you no longer need the items in your order, you may request cancellation at bookstore.colostate.edu/cancel.\n\nIf you need additional time or have questions about your order, please reply to this email before {restockDate} so we can assist you.\n",
      "note": "Final pickup reminder sent. Initial reminder sent {firstReminderDate}. Order scheduled for restock on {restockDate}",
      "fields": {
        "pickup": true,
        "finalPickup": true
      }
    },
    "authorizedPickupPerson": {
      "label": "Authorized Pickup Person",
      "subject": "[CSU Bookstore] Authorized Pickup Person Added - Order #{orderNumber}",
      "body": "We have added a note to your order authorizing {authorizedPerson} to pick up order #{orderNumber} on your behalf.\n\nPlease provide the authorized person with the order number so our team can locate your order quickly.\n\nPick-Up Location/Hours\n\nThe pickup counter is located on the lower level of the CSU Bookstore inside the Lory Student Center on the CSU Campus. Our pickup counter is open Monday–Friday, 8:00 a.m. – 4:00 p.m. \n\nAs a reminder, orders must be picked up within 28 days of the initial pick-up notification. Orders not collected within that timeframe may be returned to inventory and refunded to the original payment method.\n\nIf you need to update or remove this authorization, please reply to this email.",
      "note": "Customer authorized {authorizedPerson} to pick up the order on their behalf. Customer notified via email on {generatedDate}",
      "fields": {
        "authorizedPickup": true,
        "skipReplyHelp": true,
        "noteIncludesGeneratedDate": true,
        "signatureInNote": true
      }
    },
    "addressProblem": {
      "label": "Address problem",
      "subject": "Address confirmation needed for your CSU Bookstore order #{orderNumber}",
      "body": "We need to confirm your shipping address before we can continue processing your order. Please reply with your complete delivery address, including any apartment or unit number.",
      "note": "Emailed customer to request corrected shipping address",
      "fields": {}
    },
    "paymentIssue": {
      "label": "Payment issue",
      "subject": "Payment update needed for your CSU Bookstore order #{orderNumber}",
      "body": "We were unable to process the payment for your order. Please contact the CSU Bookstore so we can help update your payment information. For your security, do not send card information by email.",
      "note": "Emailed customer regarding payment issue and requested contact",
      "fields": {}
    },
    "onCampusDelivery": {
      "label": "On Campus Delivery - Changing to PUAS",
      "subject": "CSU Bookstore order #{orderNumber} - Changed to Pick Up at Store",
      "body": "To help support a more sustainable CSU, the CSU Bookstore is updating orders shipping to residence halls to Pick Up at Store. \n\nShipping to on-campus residence halls can result in unnecessary delays — sometimes adding an extra business day for delivery. By switching to in-store pickup, we can reduce packaging waste, lower delivery emissions, and get your order to you faster. \n\nYour order will be available for pickup at the CSU Bookstore inside the Lory Student Center during regular business hours. You may also have a friend or roommate pick up your order on your behalf — just provide them with your name and order number, and reply to this email to let us know they are authorized to do so. \n\n If you have a circumstance that makes in-store pickup difficult (such as illness, a mobility limitation, or a work-schedule conflict), simply reply to this email and we'll be happy to ship your order instead for our standard $9.99 shipping fee. Please note that shipping times may take 1-2 business days, as packages must first go through our carrier’s processing systems. \n\n Thank you for supporting a more sustainable and efficient campus community.",
      "note": "Emailed customer to notify of change to pick up at store (On campus delivery)",
      "fields": {}
    }
  },
  "sharedText": {
    "greeting": "Hello {customer},",
    "replyHelp": "Please reply to this email if you have any questions.",
    "missingProductName": "[product name]",
    "additionalNote": "Additional note: {customNote}",
    "substitutionPrompt": "Please reply with the substitution you prefer, or let us know if you would rather cancel the unavailable item.",
    "honorOriginalPrice": "I will honor the price of {originalPrice} for any of the options listed above.",
    "restockExpectedEmail": "We are expecting additional inventory on or around {expectedRestockDate}.",
    "restockQuestions": "Would you like us to hold your order until the item arrives?\n\nWould you prefer that we cancel the item from your order?",
    "restockDeadlineEmail": "If we do not hear from you by {restockResponseDeadline}, we will cancel the item from your order.",
    "restockNote": "Advised expected restock date of {expectedRestockDate} and requested response by {restockResponseDeadline}. If no response, item will be canceled.",
    "stockOnlyEmail": "Because this is the only item on your order, the order will be canceled if the unavailable item cannot be fulfilled.",
    "stockMoreEmail": "The other items on your order will still be prepared for fulfillment.",
    "stockOnlyNote": "Only item on order; order will be canceled if the unavailable item cannot be fulfilled",
    "stockMoreNote": "Other items on order will be prepared for fulfillment",
    "dayOneDetailsFallback": "This update is for “{dayOneTitle}” for {courseName} on order #{orderNumber}.",
    "dayOneOnlyEmail": "Because this is the only title on the order, the entire order is being canceled. Your payment method has not been charged.",
    "dayOneMoreEmail": "This Day One Access title cannot be fulfilled through the Bookstore order. The remaining titles/items on the order will be prepared for fulfillment.",
    "dayOneNoteLead": "Emailed customer regarding Day One Access title “{dayOneTitle}” for {courseName}",
    "dayOneOnlyNote": "Entire order canceled; payment method was not charged",
    "dayOneMoreNote": "Title cannot be fulfilled through order; remaining items will be prepared for fulfillment",
    "footer": "The CSU Bookstore is owned and operated by Colorado State University and returns all revenues to CSU for student programs and services."
  },
  "deadlineText": {
    "requestEmail": "Please reply by {deadlineDate} at {deadlineTime}.",
    "requestNote": "requested response by {deadlineDate} at {deadlineTime}.",
    "actions": {
      "item": {
        "email": "If we do not hear from you by then, the unavailable item will be canceled.",
        "note": "If no response, unavailable item will be canceled."
      },
      "order": {
        "email": "If we do not hear from you by then, the entire order will be canceled.",
        "note": "If no response, entire order will be canceled."
      },
      "hold": {
        "email": "If we do not hear from you by then, we will continue to hold your order until we hear from you.",
        "note": "If no response, order will remain on hold until customer responds."
      }
    }
  },
  "emptySubstitutions": [
    "• [product name] — [price]",
    "• [product name] — [price]",
    "• [product name] — [price]"
  ],
  "signatures": {
    "student": {
      "label": "Student name",
      "email": "Thank you,\n{employee}\nCSU Bookstore\nOnline Retail Student Employee\nbookstoreorders@colostate.edu\n(970) 491-0904"
    },
    "onlineRetail": {
      "label": "CSU Bookstore Online Retail",
      "name": "CSU Bookstore Online Retail",
      "email": "Thank you,\nCSU Bookstore Online Retail\nbookstoreorders@colostate.edu\n(970) 491-0904"
    }
  },
  "productUrlValidation": {
    "warning": "Please use the public-facing product URL (vanity URL) instead of an internal catalog URL.",
    "blockedOutput": "Correct the product URL before generating or copying this email."
  }
};
